name: 'Disparar Pipeline do Jenkins'

on:
  push:
    branches:
      - main # Dispara a chamada ao Jenkins a cada push na branch main
  workflow_dispatch: # Permite também o disparo manual caso queira testar pela interface do GitHub

jobs:
  trigger-jenkins:
    # IMPORTANTE: Como seu Jenkins está rodando no localhost:8080 (sua máquina física),
    # usamos o runner local (self-hosted) para conseguir acessar o localhost com sucesso!
    runs-on: self-hosted

    steps:
      - name: Disparar Job no Jenkins
        uses: appleboy/jenkins-action@master
        with:
          url: "http://localhost:8080" # Endereço do seu servidor Jenkins local
          job: "exercicio1-ci" # Nome exato do seu Job/Pipeline no Jenkins
          user: ${{ secrets.JENKINS_USER }} # Configurado em Settings -> Secrets and variables -> Actions
          token: ${{ secrets.JENKINS_TOKEN }} # Token de API gerado no perfil do usuário no Jenkins
